### PR TITLE
Fixed option

### PR DESCRIPTION
**Pull request by polluks**
vbcc uses `-O` + number only

### CODE REVIEW

**Comment by niklasekstrom** [comment]
Excellent, thanks for pointing this out, I had completely missed that.

Do you know if -O2 preferable over -O3 or -O4?

**Comment by polluks** [comment]
I asked Volker for better option checking in vc. His vbcc.pdf says:
-O2 will activate most optimizations (at the moment -O=1023 -schedule).
-O3 will activate all optimizations (at the moment -O=~0 -schedule).
-O4 will activate full cross-module-optimization.

**Comment by patrikaxelsson** [comment]
-O2 is usually a good compromise between binary size and speed for vbcc.

Another good flag is -sc which makes it generate pc relative code in many cases, which makes the code smaller and faster. Only downside is that the code must be reachable with 16-bit offsets, but at ~8kB this device is not anywhere near any limit.

On topic of optimization, most of the cpu time is spent waiting on CIA access plus the “hot loops” are written in assembler, so it should not make any difference.

**Comment by patrikaxelsson** [comment]
I meant to say that it should not make much difference :). Any is too definitive for something not certain.

**Pull request merged**
